spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/attendance
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
  main:
    allow-circular-references: true